<a href="https://colab.research.google.com/github/MikolajKocik/GoogleColab/blob/master/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
np.__version__


'1.26.4'

funkcja dir() ---> do przeglądania wszystkich artrybutów, metod

In [6]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

1D Array

In [7]:
x = np.array([1, 3])
x

array([1, 3])

In [8]:
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

Wymiar naszej tablicy

In [10]:
x.ndim

1

In [11]:
x.shape

(2,)

In [13]:
x.size

2

In [14]:
x.dtype

dtype('int64')

In [17]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [18]:
x.dtype

dtype('float64')

2D Array

In [20]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [21]:
x.ndim

2

In [22]:
x.shape

(2, 2)

In [24]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [25]:
x.shape

(2, 3)

3D Array

In [31]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

      [[4, 1, 3],
       [4, 2, 1]],

    [[3, 2, 1],
     [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [28]:
x.ndim

3

In [32]:
x.shape

(3, 2, 3)

Typy danych

In [33]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [36]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [37]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [39]:
A = np.array([1, 2, 3], dtype ='complex')
A.dtype

dtype('complex128')

In [40]:
A = np.array([1.0, 2.7, 3.3], dtype ='int')
A.dtype

dtype('int64')

In [41]:
A

array([1, 2, 3])

In [42]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [43]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

<ipython-input-43-27ab11b0e872>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 230 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A = np.array([24, 120, 230], dtype=np.int8)


dtype('int8')

In [44]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

Tworzenie tablic

In [45]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [48]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [53]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [55]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [56]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [57]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

"-1" python dobiera odpowiednią liczbę kolumn jaka ma być

In [59]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [63]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [64]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [65]:
A + B

array([6, 0, 7, 4])

In [66]:
A - B

array([0, 2, 1, 0])

In [67]:
A * B

array([ 9, -1, 12,  4])

In [68]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [69]:
A + 3

array([6, 4, 7, 5])

In [70]:
2 * A

array([6, 2, 8, 4])

In [71]:
A + 3*B

array([12, -2, 13,  8])

In [72]:
np.add(A, B)

array([6, 0, 7, 4])

In [74]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [75]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [76]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

Mnożenie macierzowe

In [79]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [80]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])