<a href="https://colab.research.google.com/github/MikolajKocik/GoogleColab/blob/master/Kopia_notatnika_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Podstawy

In [2]:
import numpy as np
np.__version__


'1.26.4'

funkcja dir() ---> do przeglądania wszystkich artrybutów, metod

In [3]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

# 1D Array

In [4]:
x = np.array([1, 3])
x

array([1, 3])

In [5]:
print(x)

[1 3]


In [6]:
type(x)

numpy.ndarray

Wymiar naszej tablicy

In [7]:
x.ndim

1

In [8]:
x.shape

(2,)

In [9]:
x.size

2

In [10]:
x.dtype

dtype('int64')

In [11]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [12]:
x.dtype

dtype('float64')

# 2D Array

In [13]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [14]:
x.ndim

2

In [15]:
x.shape

(2, 2)

In [16]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [17]:
x.shape

(2, 3)

# 3D Array

In [18]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

      [[4, 1, 3],
       [4, 2, 1]],

    [[3, 2, 1],
     [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [19]:
x.ndim

3

In [20]:
x.shape

(3, 2, 3)

# Typy danych

In [21]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [22]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [23]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [24]:
A = np.array([1, 2, 3], dtype ='complex')
A.dtype

dtype('complex128')

In [25]:
A = np.array([1.0, 2.7, 3.3], dtype ='int')
A.dtype

dtype('int64')

In [26]:
A

array([1, 2, 3])

In [27]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [28]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

<ipython-input-28-27ab11b0e872>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 230 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A = np.array([24, 120, 230], dtype=np.int8)


dtype('int8')

In [29]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

# Tworzenie tablic

In [30]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [36]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [38]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [39]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [40]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

"-1" python dobiera odpowiednią liczbę kolumn jaka ma być

In [42]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [44]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Podstawowe operacje na tablicach

In [45]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [46]:
A + B

array([6, 0, 7, 4])

In [47]:
A - B

array([0, 2, 1, 0])

In [48]:
A * B

array([ 9, -1, 12,  4])

In [49]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [50]:
A + 3

array([6, 4, 7, 5])

In [51]:
2 * A

array([6, 2, 8, 4])

In [52]:
A + 3*B

array([12, -2, 13,  8])

In [53]:
np.add(A, B)

array([6, 0, 7, 4])

In [54]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [55]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [56]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

# Mnożenie macierzowe

In [57]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [58]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [59]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [60]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [61]:
X @ Y

array([[  3,   6],
       [-12,   0]])

# Generowanie liczb pseudolosowych

In [62]:
np.random.seed(0)

Bez podania argumentu zwraca losową liczbę rozkładu normalnego

In [63]:
np.random.randn()

1.764052345967664

In [64]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [65]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

Rozkład jednostajny na przedziale

In [66]:
np.random.rand(10, 2)

array([[0.19658236, 0.36872517],
       [0.82099323, 0.09710128],
       [0.83794491, 0.09609841],
       [0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552],
       [0.73926358, 0.03918779],
       [0.28280696, 0.12019656],
       [0.2961402 , 0.11872772],
       [0.31798318, 0.41426299],
       [0.0641475 , 0.69247212]])

Zwraca losową liczbe w zakresie do 10

In [67]:
np.random.randint(10)

3

In [68]:
np.random.randint(low=10, high=101)

30

In [69]:
np.random.randint(low=10, high=101, size=10)

array([91, 60, 37, 24, 51, 68, 75, 46, 20, 96])

In [70]:
np.random.choice([4, 2, 1, 3, 5])

3

In [71]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [72]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Zmienia dane przez przetasowanie

In [73]:
np.random.shuffle(data)
data

array([5, 1, 4, 9, 8, 6, 7, 0, 3, 2])

# Podstawowe funkcje

In [74]:
np.exp(1)

2.718281828459045

In [75]:
np.sqrt(9)

3.0

In [76]:
np.all([2, 3, 1])

True

In [77]:
np.any([1, 2, 1])

True

In [78]:
bool(0)

False

In [79]:
bool(1.3)

True

In [80]:
A = np.random.rand(5)
A

array([0.02010755, 0.82894003, 0.00469548, 0.67781654, 0.27000797])

In [81]:
np.argmax(A)

1

In [82]:
A[np.argmax(A)]

0.8289400292173631

In [83]:
np.argmin(A)

2

In [84]:
np.argsort(A)

array([2, 0, 4, 3, 1])

In [85]:
np.max(A)

0.8289400292173631

In [86]:
np.min(A)

0.004695476192547066

In [87]:
np.median(A)

0.27000797319216485

In [88]:
np.std(A)

0.33786931210140275

# Indeksowanie, Wycinanie

In [89]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Przykład wycinania indeksów

In [89]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [90]:
A[2] # wycinamy index '2'

2

In [91]:
A[2: ]  # wycinamy od indexu '2' do końca

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [92]:
A[:2] # wycinamy do indexu '2'

array([0, 1])

In [94]:
A[[0, 2]] # wycinamy indexy '0' i '2'

array([0, 2])

In [ ]:
A[-1] # zwraca ostatni index z listy